name: ⚡ Arcane Rust Rituals

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define mystical permissions for the digital realm
permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  ROCKSDB_LIB_DIR: /usr/lib/x86_64-linux-gnu
  ROCKSDB_STATIC: 1
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  summoning:
    name: 🕯️ Summon and Test the Digital Essence
    runs-on: ubuntu-latest

    steps:
    - name: 🌒 Channel the Repository
      uses: actions/checkout@v4

    - name: ⚔️ Install Mystical Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y librocksdb-dev clang

    - name: ⛧ Invoke Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt
        override: true

    - name: 🐍 Summon Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: 📓 Cache Ancient Knowledge
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: 🔍 Verify Sacred Format
      run: cargo fmt -- --check

    - name: 🕯️ Invoke Clippy's Wisdom
      run: cargo clippy -- -D warnings

    - name: ⚡ Forge the Artifacts
      run: cargo build --verbose

    - name: 🗝️ Perform the Test Rituals
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        ./tests/run_local_tests.sh 